# Generated by Django 5.0.6 on 2026-05-09 22:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task', models.CharField(max_length=255)),
                ('frequency', models.CharField(choices=[('daily', 'daily'), ('weekly', 'weekly'), ('biweekly', 'biweekly'), ('monthly', 'monthly'), ('quarterly', 'quarterly'), ('semi_annual', 'semi_annual'), ('annual', 'annual')], default='monthly', max_length=20)),
                ('next_due', models.DateTimeField()),
                ('last_performed', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='equipment.equipment')),
            ],
        ),
    ]
