# Generated by Django 5.0.6 on 2026-05-09 22:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('supplier', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('maintenance', 'maintenance'), ('service', 'service'), ('warranty', 'warranty'), ('lease', 'lease')], default='maintenance', max_length=20)),
                ('status', models.CharField(choices=[('active', 'active'), ('expiring', 'expiring'), ('expired', 'expired'), ('cancelled', 'cancelled')], default='active', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('sla_response_hours', models.IntegerField(blank=True, null=True)),
                ('sla_resolution_hours', models.IntegerField(blank=True, null=True)),
                ('penalties', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True)),
                ('compliance_score', models.IntegerField(blank=True, default=100, null=True)),
                ('document_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
